name: justicia_administrativa_web
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # UI and Navigation
  cupertino_icons: ^1.0.8
  go_router: ^15.2.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  
  # State Management
  provider: ^6.1.5
  
  # Responsive Design
  responsive_builder: ^0.7.1
  
  # Media and Assets
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  
  # Utilities
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_map: ^8.1.1
  mailer: ^6.1.0
  flutter_hooks: ^0.21.2
  responsive_sizer: ^3.3.1
  flutter_layout_grid: ^2.0.8
  expandable: ^5.0.1
  flutter_slidable: ^4.0.0
  sliver_tools: ^0.2.12
  flutter_staggered_animations: ^1.1.1
  glass_kit: ^4.0.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.1

# Flutter specific configuration
flutter:
  # Material Icons
  uses-material-design: true

  # Asset configuration
  assets:
    - assets/images/
    - assets/images/blog/ # <-- Line added for blog images
    - assets/icons/
    - assets/fonts/

  # To add custom fonts to your application, add a fonts section here.
  # Since we're using Google Fonts, we don't need to manually add fonts.
  # fonts:
  #   - family: IBMPlexSans
  #     fonts:
  #       - asset: fonts/IBMPlexSans-Regular.ttf
  #       - asset: fonts/IBMPlexSans-Medium.ttf
  #         weight: 500
  #       - asset: fonts/IBMPlexSans-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/IBMPlexSans-Bold.ttf
  #         weight: 700